import os
import json
import requests

# Read the environment variable passed by GitHub
api_key = os.environ.get("GOOGLE_API_KEY")

if not api_key:
    print("Error: GOOGLE_API_KEY environment variable is empty or missing.")
    exit(1)

# Target the official full qualified production model path name directly
url = f"https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent?key={api_key}"

languages = ["English", "Spanish", "French", "German", "Japanese", "Italian", "Chinese", "Korean"]

prompt = (
    f"Generate a JSON object with a key 'words' containing a list of objects. "
    f"Each object must have 'lang', 'word', and 'translation'. "
    f"Provide one interesting word for each: {', '.join(languages)}. "
    f"Return ONLY raw JSON text matching this schema. Do not wrap in markdown text blocks."
)

payload = {
    "contents": [{
        "parts": [{
            "text": prompt
        }]
    }],
    "generationConfig": {
        "responseMimeType": "application/json"
    }
}

headers = {
    "Content-Type": "application/json"
}

try:
    print("Sending fully qualified direct request to Gemini v1 API...")
    response = requests.post(url, json=payload, headers=headers)
    
    # Check if request succeeded
    if response.status_code != 200:
        raise Exception(f"API returned error status {response.status_code}: {response.text}")
        
    response_json = response.json()
    
    # Extract the raw text generated by the model
    raw_text = response_json['candidates'][0]['content']['parts'][0]['text'].strip()
    
    # Validate it is valid JSON syntax and save it
    data = json.loads(raw_text)
    
    with open('words.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        
    print("Successfully generated and saved words.json via production API endpoint!")

except Exception as e:
    print(f"Error occurred during generation: {e}")
    exit(1)
